spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/postgres
    username: postgres
    password: qwerty
  flyway:
    url: jdbc:postgresql://localhost:1234/postgres
    user: postgres
    password: qwerty
    locations: classpath:db/migration